server {
    listen ${NGINX_PORT};

    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";

    location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|svg|woff2)$ {
        root /var/www/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
